# Generated by Django 4.2.11 on 2024-08-22 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
        migrations.AddField(
            model_name='mtroutersmodel',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filtersmodel', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='mtroutersmodel',
            name='httpconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.httpccmmodel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='mtroutersmodel',
            name='smppconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smppccmmodel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='mtinterceptor',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filtersmodel', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='moroutersmodel',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filtersmodel', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='moroutersmodel',
            name='httpconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.httpccmmodel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='moroutersmodel',
            name='smppconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smppccmmodel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='mointerceptor',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filtersmodel', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
